### ISSUE TITLE
Naming conventions and packaging for processors and scanners

### ISSUE THREAD

**Issue by hexastax** [nsoft/jesterj#12]
I'd like to propose the following conventions:
1. For processors, use a verb. E.g. ReformatDateTime (instead of SimpleDateTimeReformater - that's a reformatter anyway..), SendToSolrCloud instead of SendToSolrCloudProcessor, etc.
2. Could use verbs for scanners, too, e.g.: ScanJdbcSource, ScanS3, ScanFileSystem.  And perhaps ScanFileSystemIncremental...

For processors, ideally the groupings of related processors would reside in a sub-package. The currently used org.jesterj.ingest.processors will fill up quickly and become a hard to manage long list.

Ditto with scanners.  In fact, I propose that the more complex scanners be placed into their own gradle projects.  The simpler scanners could still live under 'ingest' although it seems cleaner to split each one into a separate project ...

**Comment by nsoft** [comment]
Definately consistent naming should be discussed and then implemented.

**Comment by hexastax** [comment]
Possible renamings

ElasticNodeSender -> SendToElasticNode
SendToSolrCloudProcessor -> SendToSolrCloud
SimpleDateTimeReformatter -> ReformatDateTime
TikaProcessor -> ExtractMetadataAndText

**Comment by nsoft** [comment]
I want the Tika step to have "Tika" in the name. It's a recognizable brand with known capabilities (which we should expose more of. 

I tend to prefer actor naming rather than verb naming (but I agree we don't want everything ending in Processor which is just a waste of screen space) 

ElasticNodeSender
SolrCloudSender
SimpleDateTimeFormatter   
TikaTextExtractor

withProcessor(SendToSolrCloud) looks funny because Processor is a noun and so you expect to pass a noun to it...

withProcessor(SolrCloudSender) seems more natural or "fluent" to me. 

What do you think?

**Comment by hexastax** [comment]
That sounds good to me and I think it's in line with the scanner convention where it's "something"Scanner (a descriptive noun rather than a verb).

Should we think about the distinctions between processors and steps?  Would an end-user mostly deal with processors and never with steps, or sometimes with steps?

**Comment by nsoft** [comment]
I wouldn't rule out users writing custom steps, but they should inherit from our StepImpl class if they do, and it would be tricky for them not to mess up the basic infrastructure provided. Generally custom code should implement DocumentProcessor. 

This discussion seems settled, closing.
