### ISSUE TITLE
Convention/pattern for exception generation and handling

### ISSUE THREAD

**Issue by hexastax** [nsoft/jesterj#25]
- Checked vs. unchecked exceptions
  -- E.g. CyclicGraphException extends RuntimeException; ConfigurationException extends JesterjException
- Should all exceptions derive from JesterjException (which extends Exception)
- Does there need to be a JesterjRuntimeException

**Comment by nsoft** [comment]
We discussed this on skype, I think we came to a conclusion of Checked exceptions for our exceptions that aggregate several exceptions and until we find a specific needful case using appropriate JDK runtime exceptions such as IllegalArgumentException when it's a programmer error or other unrecoverable situation. If you agree I think this is closed.

**Comment by hexastax** [comment]
Well, there are currently existing exceptions CyclicGraphException and StepNotFoundException which are unchecked/runtime.  Perhaps these should be subclasses of JesterjException?

**Comment by nsoft** [comment]
Whoops forgot about those :) They should probably be converted to IllegalStateException with a message about why.

**Comment by hexastax** [comment]
So, to seek some control over this :) What happens when an IllegalStateException is thrown during plan execution? Who catches it and where does the exception show up?

**Comment by nsoft** [comment]
The two exceptions I am talking about replacing only occur during the construction of a plan from builders, so at that time it's reasonable to fail the construction. Right now we don't have a "load a plan while presently running" feature, only load plan on startup. Dedicated checked exceptions might be applicable I suppose in the case where we need to recover and keep going. For now they're fatal errors.

The general distinction for checked vs unchecked is whether or not we expect to recover. However, theres a variation on this with steps/scanners etc. Since they have thread pools the definition of "not recover" should be execution completes and the thread is returned to the pool (hopefully with an error logged for the exception), not a JVM exit for anything less than java.lang.Error. 

java.lang.Error subclasses should always kill the vm. They include things like out of memory, or class linking problems after which we could have strange memory states and might produce weird subsequent failures or even worse emit invalid documents.

**Comment by hexastax** [comment]
Hm, well there are ways of handling checked exceptions as recoverable or unrecoverable. What they bring to the table is a way to control what happens under which scenario upon an error. I usually tend to lean strongly toward API's that are explicit on what exceptions they throw. Our engine can decide what to do for which case.  I imagine mostly it would be catching and logging, perhaps also catching and displaying the message to the user.

If we have a lot of unchecked exceptions floating around, it's harder to do this orderly massaging of exceptions, IMO.
